### ISSUE TITLE
I can´t read many fit files at the same time.

### ISSUE THREAD

**Issue by AaronMulvey** [grimbough/FITfileR#12]
Hi there,
I am trying to read multiple fit files at the same time. I have a directory with 300 files (200Mg). When I read 20 files in R with the readfitfile () function I use 1gb of memory. I don't know if you could explain what happens, here is my code:

path <- 'C:/Users/aaron/OneDrive/Escritorio/TFG/Deportistas/Tarea Atleta/Paula Suarez'

files <- list.files(path, full.names = TRUE)

data <- archivos_T.A[1:20]

read_data <- readFitFile(data)

**Comment by grimbough** [comment]
I'm not sure I follow your code.  `readFitFile()` shouldn't take a vector of file names.  It's only designed to take a single path, and I'd expect it to fail inelegantly if you try to give it more.  He's what happens for me using the four example files distributed with the package:

```r
library(FITfileR)
files <- list.files(system.file("extdata", "Activities", package = "FITfileR"), 
                    full.names = TRUE)
files
#> [1] "/mnt/data/R-lib/4.0.3-bioc_3.12/FITfileR/extdata/Activities/garmin-edge500-ride.fit"
#> [2] "/mnt/data/R-lib/4.0.3-bioc_3.12/FITfileR/extdata/Activities/garmin-edge530-ride.fit"
#> [3] "/mnt/data/R-lib/4.0.3-bioc_3.12/FITfileR/extdata/Activities/garmin-fenix6-swim.fit" 
#> [4] "/mnt/data/R-lib/4.0.3-bioc_3.12/FITfileR/extdata/Activities/tomtom-runner3-ride.fit"

readFitFile(files)
#> Error in file(fileName, "rb"): invalid 'description' argument
```

You probably want to use something like `lapply(files, readFitFile)` to read the complete set of files.

It's true that the objects created by `readFitFile()` are pretty big compared to the original files, but it's not quite as bad as R/Rstudio makes it appear.  There's some slightly complex reuse of memory inside the objects, which confuses the standard memory counter.  If you use `pryr::object_size()` you'll see it's actually using about 20-25% of the reported amount e.g.

```r
fenix6 <- readFitFile(files[3])

## Comparing the standard R size with pryr
print(object.size(fenix6), units = "MB")
#> 15.3 Mb
pryr::object_size(fenix6)
#> 3.32 MB

## direct size comparison in bytes
pryr::compare_size(fenix6)
#>     base     pryr 
#> 16036912  3317440
```

Nonetheless, if memory is still an issue I'd recommend only extracting the parts of the files you want after each read, which will give you a `data.frame` of all the messages of a particular type. This should be much more efficient.  For example, if you want the GPS coordinates or heart rate data from a file, they're stored in the "records" message type and you can access those with `records()`.  The code below gets the records from each of the four files and throws away the FitFile objects after each read. This should be more efficient from a memory standpoint, and you could modify the function further to get only the columns you really need if you want to make it smaller still.

```r
## read a each file and extract only the 'records'.  
records_list <- lapply(files, 
                       function(file) {
                         ## modify this if you need something else
                         records(readFitFile(file))
                       })
## name the list elements after the files we read
names(records_list) <- basename(files)

## the list of records is much smaller 
pryr::object_size(records_list)
#> 3.99 MB

## examine the records from the first file
records_list[[1]]
#> $record_1
#> # A tibble: 4,923 x 8
#>    timestamp           position_lat position_long distance altitude speed
#>    <dttm>                     <dbl>         <dbl>    <dbl>    <dbl> <dbl>
#>  1 2017-02-05 09:31:11         49.4          8.70     62.4     233.  5.23
#>  2 2017-02-05 09:31:12         49.4          8.70     68.2     233   5.84
#>  3 2017-02-05 09:31:13         49.4          8.70     74.1     232.  5.94
#>  4 2017-02-05 09:31:14         49.4          8.70     80.6     232   6.43
#>  5 2017-02-05 09:31:15         49.4          8.70     86.6     231.  6.05
#> # … with 4,918 more rows, and 2 more variables: heart_rate <int>,
#> #   temperature <int>
#> 
#> $record_2
#> # A tibble: 3 x 4
#>   timestamp           altitude heart_rate temperature
#>   <dttm>                 <dbl>      <int>       <int>
#> 1 2017-02-05 09:30:53     237.         89          10
#> 2 2017-02-05 09:30:54     237.         91          10
#> 3 2017-02-05 09:30:57     237.         92          10
#> 
#> $record_3
#> # A tibble: 12 x 6
#>    timestamp           distance altitude speed heart_rate temperature
#>    <dttm>                 <dbl>    <dbl> <dbl>      <int>       <int>
#>  1 2017-02-05 09:30:58     1.56     236.  1.56         93          10
#>  2 2017-02-05 09:31:06    35.0      236   5.15         93          10
#>  3 2017-02-05 09:31:07    40.2      235.  5.16         94          10
#>  4 2017-02-05 09:31:08    45.8      235   5.60         96          10
#>  5 2017-02-05 09:31:09    51.5      234.  5.69         98          10
#>  6 2017-02-05 09:31:10    57.1      234   5.66         99          10
#> # … with 6 more rows
```

**Comment by cocovelo** [comment]
Hi, thank you so much for spending the time to write the FITfileR package. I'm having a similar(ish) issue to the one above in that I'm having trouble reading in multiple files and wondered if you could give me any clues as to what I'm doing wrong?

I'm trying to read in a batch of ~3000 Garmin-derived .fit files using FITfileR, by first creating a list of all the .fit files:
`listoffiles <- dir(path = directory, pattern = ".fit")`

Then using either lapply or a for loop to read them one-by-one into R (both methods are giving me the same error) using the following:
`readfiles <- sapply(listoffiles, readFitFile)` or
```
readfiles <- tibble()
x = 0
for(i in 1:length(listoffiles)) {
    readfiles <- readFitFile(listoffiles[i])
    x <- x+1
    cat('Reading file', i, 'of', length(listoffiles),'\n')
    }
```


The command will run and appears to read in all of the files, but at the end it gives the following error and my output `readfiles` is empty:
```
Error in (function (classes, fdef, mtable)  : 
unable to find an inherited method for function ‘globalMessageNumber’ for signature ‘"NULL"’ 
```

Any help would be really appreciated. Thanks and best wishes,
Colin
https://github.com/cocovelo

**Comment by cocovelo** [comment]
@cocovelo

**Comment by grimbough** [comment]
@cocovelo I think the first place to start is to test with only a single file. I've not seen the error before so it's hard to say if it's likely to be all files from your device, or just one unusual file. 

Try reading just `listoffiles[1]` and see if the error occurs. If not, perhaps looking at the i-th file (the value of the loop index when the error occurs) would be a good choice. If you can pin down the file perhaps you can share them with me?

Also note that in the for loop you are overwriting `readfiles` each time, so it's not necessarily surprise it is empty after the error.

**Comment by cocovelo** [comment]
Hi @grimbough thanks very much for your reply. I'll try again today and let you know if it works or not. Reading in a single .fit file does work so I know it's not a problem related to the device. Actually I had a script that was able to read in and analyse a subset of 19 .fit files so my suspicion is that there are one or more problem files in the full set of ~3000. I'd be happy to share them with you if I can identify the problematic one(s). Also thanks for highlighting the for loop issue! Cheers.

**Comment by cocovelo** [comment]
@grimbough sorry haven't had time yet to look at this again. I will do shortly.

**Comment by cocovelo** [comment]
@grimbough sorry to have bothered you. The errors I was getting were because in creating my list of .fit files with
`listoffiles <- dir(path = directory, pattern = ".fit")`
I was capturing a non-.fit file in there too. Thanks for your help and thanks again for taking the time to develop and share this package.
