### ISSUE TITLE
Install fails on R4.04, x86_64

### ISSUE THREAD

**Issue by dakiphart** [grimbough/FITfileR#25]
* checking for file ‘/tmp/RtmpZUbsRf/remotes8aeb3c02/grimbough-FITfileR-f35947e/DESCRIPTION’ ... OK
* preparing ‘FITfileR’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘FITfileR_0.1.6.tar.gz’
Installing package into ‘/home/dakiphart/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘FITfileR’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /tmp/RtmpbAEviu/R.INSTALLc84456c9d56/FITfileR/R/allMethods.R:37:43: unexpected '>'
36:         
37:         original <- object@fields[[ i ]] |>
                                              ^
ERROR: unable to collate and parse R files for package ‘FITfileR’
* removing ‘/home/dakiphart/R/x86_64-pc-linux-gnu-library/4.0/FITfileR’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpZUbsRf/file8ae43837cd6/FITfileR_0.1.6.tar.gz’ had non-zero exit status
> R.Version()
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.4"

$year
[1] "2021"

$month
[1] "02"

$day
[1] "15"

$`svn rev`
[1] "80002"

$language
[1] "R"

$version.string
[1] "R version 4.0.4 (2021-02-15)"

$nickname
[1] "Lost Library Book"

**Comment by griffindatasci** [comment]
same issue and unable to upgrade R as yet (work computer)

**Comment by dakiphart** [comment]
Upgrading to R version 4.2.2 solved my problem. Thanks for the help!
