### ISSUE TITLE
Error: Tibble columns must have compatible sizes.

### ISSUE THREAD

**Issue by WoodGrove** [grimbough/fitFileR#3]
Im trying to read a fit file from a fenix 6s. It looks like it generates an error when trying to read the device info section. I have a Running Dynamic pod and Garmin Pulse Strap HRM4 connected to the watch.

[4990184618.zip](https://github.com/grimbough/fitFileR/files/4882892/4990184618.zip)
readFitFile("data/raw/4990184618.fit")
Error: Tibble columns must have compatible sizes.
* Size 6: Column `29`.
* Size 32: Column `17`.
i Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/tibble_error_incompatible_size>
Tibble columns must have compatible sizes.
* Size 6: Column `29`.
* Size 32: Column `17`.
i Only values of size one are recycled.
Backtrace:
 1. fitFileR::readFitFile("data/raw/4990184618.fit")
 2. fitFileR:::.readFile(fileName)
 3. fitFileR:::.readMessage.data(con, message_defs[[defIdx]], compressed_timestamp = FALSE)
 5. tibble:::as_tibble.list(message)
 6. tibble:::lst_to_tibble(x, .rows, .name_repair, col_lengths(x))
 7. tibble:::recycle_columns(x, .rows, lengths)

**Comment by grimbough** [comment]
Your Fenix6 has a lot more fields than my Edge 500! 

I've made some updates and it's able to at least read your file now:

```r
tmp <- readFitFile('/tmp/4990184618.fit')
is(tmp)
## [1] "list"   "vector"
```

There are some warnings about embedded nul strings, but I guess it might be struggling with the characters in fēnix or something in your language settings that my R code isn't coping with, but it most of the data should be there.   Let me know if there's anything that still looks messed up, the FIT file format is pretty complex!

**Comment by WoodGrove** [comment]
Thank, you! Yes the FIT format is pretty complex. I will try it out and also try to switch to English, the language encoding for Swedish does mess up things quite often.
