### ISSUE TITLE
Cannot Read File

### ISSUE THREAD

**Issue by aquilo** [grimbough/FITfileR#30]
Hi Mike

I wanted to begin some analyis of my Apple Watch training data. With the HealthFit app I've exported a training as fit file (the file is attached). When I want to read it with readFitFile I get the following error:

**Error in readBin(con, what = readInfo[[1]], signed = readInfo[[2]], size = readInfo[[3]],  : 
  invalid 'n’ argument**

**My script:**
```
if(!requireNamespace("remotes")) {
  install.packages("remotes“)
}
remotes::install_github("grimbough/FITfileR")
library(FITfileR)
fit = readFitFile("2023-10-20-111559.fit")
```

I’m not sure whether this ist a duplicate of another ticket, but I do not know how to proceed. The example files work without problems.

Adrian

**My session:**

R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.0

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] FITfileR_0.1.6 needs_0.0.3   

loaded via a namespace (and not attached):
 [1] utf8_1.2.3        R6_2.5.1          tidyselect_1.2.0  magrittr_2.0.3    remotes_2.4.2.1   glue_1.6.2        tibble_3.2.1      pkgconfig_2.0.3  
 [9] dplyr_1.1.2       generics_0.1.3    lifecycle_1.0.3   cli_3.6.1         fansi_1.0.4       vctrs_0.6.3       compiler_4.3.1    rstudioapi_0.15.0
[17] tools_4.3.1       curl_5.0.1        pillar_1.9.0      rlang_1.1.1 

[2023-10-20-111559.fit.zip](https://github.com/grimbough/FITfileR/files/13062870/2023-10-20-111559.fit.zip)

**Comment by grimbough** [comment]
Thanks for the report and example file.  This should now work in version 0.1.7:

```r
library(FITfileR)

## download and extract the example file
destfile = tempfile(fileext = ".zip")
url = "https://github.com/grimbough/FITfileR/files/13062870/2023-10-20-111559.fit.zip"
dl = download.file(url = url, destfile = destfile)
example_file = unzip(destfile, exdir = tempdir())

## read and extract the records
fitFile <- readFitFile(example_file[1])
records <- records(fitFile) 

records
#> # A tibble: 3,265 × 2
#>    timestamp           heart_rate
#>    <dttm>                   <int>
#>  1 2023-10-20 09:16:02         69
#>  2 2023-10-20 09:16:03         69
#>  3 2023-10-20 09:16:04         69
#>  4 2023-10-20 09:16:05         69
#>  5 2023-10-20 09:16:06         69
#>  6 2023-10-20 09:16:07         69
#>  7 2023-10-20 09:16:08         69
#>  8 2023-10-20 09:16:09         69
#>  9 2023-10-20 09:16:10         69
#> 10 2023-10-20 09:16:11         70
#> # ℹ 3,255 more rows
```

**Comment by aquilo** [comment]
Perfect! I really appreciate that you got this up and running so quickly. Thank you so much!
