### ISSUE TITLE
Invalid 'n' argument

### ISSUE THREAD

**Issue by nf-exphys** [grimbough/fitFileR#4]
I came across this package when looking for R packages to load fit files from my Garmin Forerunner 235, and it looks really promising! Unfortunately, I've only been able to load the garmin .fit file included in the package. When trying to load other .fit files, I've been getting this error:

Error in readBin(con = con, what = "raw", n = 3 * message$n_fields, size = 1,  : 
  invalid 'n' argument

I also get an error with the sample TomTom file, but that's a different error, so I'm not sure what's up there. Depending on which of my fit files I use, I get the above message and the warning message below, repeated 8-16 different times, though it's present after all of my fit files. 
In addition: Warning messages:
1: In readChar(con = con, nchars = n_values, useBytes = TRUE) :
  truncating string with embedded nuls

I've done my best to trouble shoot this on my own (trying different fit files, restarting RStudio, uninstalling and reinstalling R/RStudio, etc.) and haven't been able to get it to work. I've confirmed that the system.file line works, so the issue seems to be in the second of the two lines. What am I doing wrong? The code and fit file I've been using are listed below. 

library(fitFileR)
garmin_file <- system.file("extdata/Garmin.fit", package = "fitFileR")
garmin <- readFitFile(garmin_file)

test_file <- system.file("extdata/July5Easy.fit", package = "fitFileR")
test <- readFitFile(test_file)
traceback()

[July 5 Easy Run.zip](https://github.com/grimbough/fitFileR/files/4915543/July.5.Easy.Run.zip)

**Comment by grimbough** [comment]
Thanks for the interest in the package and the example file.  It's almost certainly a problem in my code rather than something you're doing wrong.  The FIT format is pretty complex with lots of options, and I only have a Garmin Edge 500 to test files from.

I'm on vacation at the moment, but I'll try to take a look at what's happen with your example file when I get a chance.

**Comment by grimbough** [comment]
It looks like your file includes some "developer data" fields, which fitFileR identifies and then ignores - that breaks the reading of everything after that point. Should be fairly straightforward to update the reading to handle that properly.

**Comment by grimbough** [comment]
You should now be able to read your file.  It's a bit of a hack, because I just skip over the 'developer data' for the moment, so you can actually use it, but assuming that's not the information you're interested in you should be able to read the rest of the contents:

```r
library(fitFileR)

## download the linked file from this issue - should work on any system
destfile = tempfile(fileext = ".zip")
url = "https://github.com/grimbough/fitFileR/files/4915543/July.5.Easy.Run.zip"
dl = download.file(url = url, destfile = destfile)
tdir = tempfile()
dir.create(tdir)
files = unzip(destfile, exdir = tdir)

## read file
fit <- readFitFile(files[1])

## examine the output
names(fit)
#>  [1] "file_id"           "file_creator"      "event"            
#>  [4] "device_info"       "device_settings"   "user_profile"     
#>  [7] "sport"             "zones_target"      "developer_data_id"
#> [10] "field_description" "record"            "lap"              
#> [13] "session"           "activity"
fit$record
#> # A tibble: 1,791 x 9
#>    timestamp           position_lat position_long distance altitude speed
#>    <dttm>                     <int>         <int>    <dbl>    <dbl> <dbl>
#>  1 2020-07-06 04:16:20    536708808   -1111771622     0        808  0.821
#>  2 2020-07-06 04:16:21    536708554   -1111771693     2.26     808. 1.39 
#>  3 2020-07-06 04:16:22    536708311   -1111771870     4.79     808. 1.39 
#>  4 2020-07-06 04:16:23    536708084   -1111772061     7.2      808. 1.70 
#>  5 2020-07-06 04:16:24    536707840   -1111772304     9.96     808. 2.02 
#>  6 2020-07-06 04:16:25    536707643   -1111772584    12.6      808. 2.36 
#>  7 2020-07-06 04:16:26    536707474   -1111772901    15.2      808. 2.36 
#>  8 2020-07-06 04:16:27    536707284   -1111773258    18.1      807. 2.82 
#>  9 2020-07-06 04:16:28    536707026   -1111773606    21.4      807. 3.06 
#> 10 2020-07-06 04:16:29    536706736   -1111773934    24.9      807. 3.42 
#> # … with 1,781 more rows, and 3 more variables: heart_rate <int>,
#> #   cadence <int>, fractional_cadence <dbl>
```

**Comment by nf-exphys** [comment]
This seems to have fixed the issue - thank you! Skipping over the developer fields is just fine with me. Anything I would've had calculated in a developer field is probably better calculated manually in R anyways. 

> You should now be able to read your file. It's a bit of a hack, because I just skip over the 'developer data' for the moment, so you can actually use it, but assuming that's not the information you're interested in you should be able to read the rest of the contents:
