### ISSUE TITLE
Cannot load package

### ISSUE THREAD

**Issue by pinodaleppo** [grimbough/FITfileR#9]
on R version 4.0.2
I have installed FITfileR as instructed. I get the following error message when calling the package:
> library(FITfileR)
Error in FUN(X[[i]], ...) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/fitFileR/R/fitFileR.rdb' is corrupt
In addition: Warning message:
In FUN(X[[i]], ...) : internal error -3 in R_decompress1

It used to work a few days ago!
Thanks
Giuseppe

**Comment by grimbough** [comment]
Sorry I missed this.  In my experience this type of error is normally resolved with a reinstallation of the package (and possibly a restart of R).
